=== weamibrahim/xml/lab2/task1/employee.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Employees (Employee*)>
<!ELEMENT Employee (Name,Addresses,Phones,Email)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Addresses (Address+)>
<!ELEMENT Address (Street, Building_No, Region, City, Country)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT Building_No (#PCDATA)>
<!ELEMENT Region (#PCDATA)>
<!ELEMENT  City (#PCDATA)>
<!ELEMENT  Country (#PCDATA)>
<!ELEMENT Phones (Phone+)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ATTLIST Phone type CDATA #REQUIRED>

=== weamibrahim/xml/lab2/task1/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="employee.css"?>
<!DOCTYPE Employees SYSTEM "employee.dtd">


<Employees>
     <Employee>
             <Name>weam</Name>
             <Addresses>
             <Address>
                   <Street>st-school</Street>
                   <Building_No>3nd</Building_No>
                   <Region>kafrelshiesh</Region>
                  <City>kafrelshiesh</City>
                   <Country>Egypt</Country>
              </Address>
               <Address>
                   <Street>st-school</Street>
                   <Building_No>3nd</Building_No>
                   <Region>kafrelshiesh</Region>
                  <City>kafrelshiesh</City>
                   <Country>Egypt</Country>
              </Address>
               </Addresses>
              <Phones>
                  <Phone type='home'>98877656</Phone>
                  <Phone type='mobile'>09987665434356</Phone>
              </Phones>
              <Email>weam@gmail.com</Email>
  </Employee>
  <Employee>
        <Name>nour</Name>
          <Addresses>
             <Address>
                   <Street>st-school</Street>
                   <Building_No>6nd</Building_No>
                   <Region>kafrelshiesh</Region>
                  <City>kafrelshiesh</City>
                   <Country>Egypt</Country>
              </Address>
               <Address>
                   <Street>st-school</Street>
                   <Building_No>6nd</Building_No>
                   <Region>kafrelshiesh</Region>
                  <City>kafrelshiesh</City>
                   <Country>Egypt</Country>
              </Address>
               </Addresses>
               <Phones>
                 <Phone type="home">9876756</Phone>
                  <Phone type="mobile">978765655434356</Phone>
              </Phones>
             <Email>nour@gmail.com</Email>
</Employee>
    <Employee>
          <Name> asmaa</Name>
          <Addresses>
             <Address>
                   <Street>st-school</Street>
                   <Building_No>9nd</Building_No>
                   <Region>kafrelshiesh</Region>
                  <City>kafrelshiesh</City>
                   <Country>Egypt</Country>
              </Address>
               <Address>
                   <Street>st-school</Street>
                   <Building_No>9nd</Building_No>
                   <Region>kafrelshiesh</Region>
                  <City>kafrelshiesh</City>
                   <Country>Egypt</Country>
              </Address>
               </Addresses>
                <Phones>
                   <Phone type="home">98877656</Phone>
                   <Phone type="mobile">897865434356</Phone>
                </Phones>
                <Email>asmaa@gmail.com</Email>
   </Employee>
 
</Employees>
